name: CI Simple

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v2
      with:
        python-version: '3.12'

    - name: Configurar caché de UV
      uses: actions/cache@v4
      with:
        path: |
          .uv-cache
          ~/.cache/uv
        key: ${{ runner.os }}-uv-${{ hashFiles('**/uv.lock') }}
        restore-keys: |
          ${{ runner.os }}-uv-

    - name: Instalar dependencias
      run: |
        uv sync
   
    - name: Generar archivo de requerimientos
      run: |
        uv export -o requirements.txt --no-header --no-hashes
        cat requirements.txt | grep -v '^\[tool\.' | sort -u > requirements.txt

    - name: Ejecutar linters
      run: |
        uv run ruff check .
        uv run ruff format --check .

    - name: Ejecutar type checking
      run: |
        uv run pyrefly check

    - name: Ejecutar tests
      run: |
        uv run pytest -v --cov=simple_rrss_ticket_categorizer --cov-report=xml
