name: Build Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v2
    
    - name: Instalar dependencias y build
      run: |
        uv sync
        uv build

    - name: Subir a Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
        body: "Build automático con UV - ${{ github.ref_name }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}